baseurl: /
languageCode: zh-cn
title: Qiyan Yang
theme: hugo-ivy
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  yangduanduan: /yangduanduan/:year/:month/:day/:slug/
  yangjinjin: /yangjinjin/:year/:month/:day/:slug/

menu:
  main:
    - name: "关于"
      url: "/about/"
      weight: 1
    - name: "端端"
      url: "/yangduanduan/"
      weight: 2
    - name: "今金"
      url: "/yangjinjin/"
      weight: 3
    - name: "类别"
      url: "/categories/"
      weight: 4
    - name: "标签"
      url: "/tags/"
      weight: 5

params:
  description: "Duanduan & Jinjin"
  footer: "&copy; [Qiyan Yang](https://yangqiyan.netlify.app) | 转载联系 yangqiyan_lena@qq.com"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"
  highlightjsVersion: "9.12.0"

markup:
  goldmark:
    renderer:
      unsafe: true