---
title: "不等式的基本性质"
author: "杨启妍"
date: '2021-08-26'
categories: 高中数学
tags: 高中数学
---

> **课程标准课程内容**：梳理等式的性质，理解不等式的概念，掌握不等式的性质。  
>
> **数学教材编写研究**：不等式的基本性质是“对称性”、“传递性”、“对加法和乘法运算保持不变性”。事实上，前二者反映了不等式的"关系的特性"，后者反映了不等式“在运算中的不变性”。等式的基本性质和不等式的基本性质刻画的都是这两方面的性质。按照“回顾、梳理—提炼—迁移”的过程，重新理解初中的等式内容，构建高中不等式内容的研究框架。 

---

等式有下面的基本性质：
$\forall a,b,c\in\mathbb{R}$，

性质1：$a=b\iff b=a$.  

性质2：$a=b\text{ 且 }b=c\implies a=c$.  

性质3：$a=b\iff a+c=b+c$.   

性质4：$a=b\implies ac=bc$.  

性质5：$a=b\text{ 且 }c\neq0\implies\frac{a}{c}=\frac{b}{c}$.  

不等式基本事实：  

1. $a>b\iff a-b>0$,  

2. $a=b\iff a-b=0$,  

3. $a<b\iff a-b<0$.  

类比等式基本性质，利用上述基本事实，可以猜想并证明下列**不等式的基本性质**：  

$\forall a,b,c,d\in\mathbb{R}$，   

> **性质1：$a>b\iff b<a$.*（对称性）* **
>
> 证明：$a>b\stackrel{基本事实}{\iff}a-b>0\stackrel{\text{实数性质}}{\iff}-(a-b)<0\text{ 即 }b-a<0\stackrel{基本事实}{\iff}b<a.$   


> **性质2：$a>b\text{ 且 }b>c\implies a>c$.*（传递性）* **
>
>证明：$a>b\text{ 且 }b>c\stackrel{基本事实}{\iff}a-b>0\text{ 且 }b-c>0\stackrel{实数性质}{\implies}(a-b)+(b-c)>0\text{ 即 }a-c>0\stackrel{基本事实}{\iff}a>c.$        


> **性质3：$a>b\iff a+c>b+c$.*（可加性）* **
>
> 证明：$a>b\stackrel{基本事实}{\iff}a-b>0\stackrel{}{\iff}(a+c)-(b+c)>0\stackrel{基本事实}{\iff}a+c>b+c.$  
>
> 注释：不等式两边加上（或减去）同一个实数，不等号方向不变。    


> **性质4：$a>b\text{ 且 }\mathop{}_{c<0}^{c>0}\implies \mathop{}_{ac<bc}^{ac>bc}$.*（可乘性）* **
>
> 证明：$a>b\stackrel{基本事实}{\iff}a-b>0\stackrel{实数性质}{\implies}\mathop{}_{当c<0时，(a-b)c<0\text{ 即 }ac-bc<0}^{当c>0时，(a-b)c>0\text{ 即 }ac-bc>0}\stackrel{基本事实}{\iff}\mathop{}_{当c<0时，ac<bc}^{当c>0时，ac>bc}.$  
> 注释：不等式两边乘以（或除以）同一个正实数，不等号方向不变；乘以（或除以）同一个负实数，不等号方向改变。 
>
> 辨析：$a>b>0\implies\frac{1}{a}<\frac{1}{b}.$ $\checkmark$   


> **性质5：$a>b\text{ 且 }c>d\implies a+c>b+d$.*（同向可加性）* ** 
>
> 证明：$a>b\text{ 且 }c>d\stackrel{基本事实}{\iff}a-b>0\text{ 且 }c-d>0\stackrel{实数性质}{\implies}(a-b)+(c-d)>0\text{ 即 }(a+c)-(b+d)>0\stackrel{基本事实}{\iff}a+c>b+d.$   
>
> 或证：$\mathop{}_{c>d}^{a>b}\stackrel{性质3、性质3}{\iff}\mathop{}_{b+c>b+d}^{a+c>b+c}\stackrel{性质2}{\implies}a+c>b+d.$
>
> 注释：两个同向不等式两边分别相加，所得不等式和原不等式方向一致。 
>
> 辨析：$a>b\text{ 且 }c>d\implies a+d>b+c.$ $\boldsymbol{\times}$   
>
> 辨析：$a>b\text{ 且 }c>d\implies a-c>b-d.$ $\boldsymbol{\times}$  
>
> 辨析：$a>b\text{ 且 }c>d\implies a-d>b-c.$ $\checkmark$    


> **性质6：$a>b>0\text{ 且 }c>d>0\implies ac>bd$.*（同向同正可乘性）* **
>
> 证明：$\mathop{}_{c>d\text{ 且 }b>0}^{a>b\text{ 且 }c>0}\stackrel{性质4、性质4}{\implies}\mathop{}_{bc>bd}^{ac>bc}\stackrel{性质2}{\implies}ac>bd.$  
>
>注释：两边都是正数的同向不等式两边分别相乘，所得不等式和原不等式方向一致。特别地，当$c=a,d=b$时，$a^2>b^2$。更可推广至如下结论：$a>b>0\implies a^n>b^n (n\in\mathbb{N^*}).$    
>
> 结论：$a>b>0\text{ 且 }c>d\text{ 且 }c>0\implies ac>bd.$    
>
> 辨析：$a>b\text{ 且 }c>d\implies ac>bd.$ $\boldsymbol{\times}$    
>
> 辨析：$a<b<0\text{ 且 }c<d<0\implies ac>bd.$ $\checkmark$  
>
> 辨析：$a>b>0\implies\frac{b}{a}<\frac{a}{b}.$ $\checkmark$   

---

练习1：若$a>b$ , $\frac{1}{a}>\frac{1}{b}$ ，则 $a>0 , b<0.$ $\checkmark$   

练习2：若$\frac{1}{a}<\frac{1}{b}<0$ ，则 $\left|a\right|<\left|b\right|\checkmark;a>b\checkmark;a+b<ab\checkmark;ab>a^2\checkmark.$   

练习3：已知$a>b>0,c<d<0,e<0$，求证：$\frac{e}{(a-c)^2}>\frac{e}{(b-d)^2}.$  

练习4：已知$a>0,b>0$，比较大小：$a^3+b^3,a^2b+ab^2.$   

练习5：已知$x>0,y>0$，比较大小：$\frac{1}{x}+\frac{1}{y},\frac{1}{x+y}.$  

练习6：已知$-1<x<y<0$，比较大小：$\frac{1}{x},\frac{1}{y},x^2,y^2.$   

练习7：已知$a>b>0$，求证：$\sqrt{a}>\sqrt{b}$；$a>\frac{a+b}{2}>\sqrt{ab}>b.$ 

练习8：已知$a>b,ab\neq0$，比较大小：$\frac{1}{a},\frac{1}{b}.$   

练习9：设$m$为实数，解关于$x$的不等式$m(x+2)<x+m.$   

练习10：已知$-2<a\leqslant3,1\leqslant b<2$，试求下列代数式的取值范围：$\left|a\right|;a+b;a-b;2a-3b;\frac{a}{b}.$   

练习11：已知$b$克糖水中含有$a$克糖$(b>a>0)$，再添加$m$克糖$(m>0)$（假设全部溶解），糖水变甜了。请将这一事实表示为一个不等式，并证明这个不等式成立。  