---
title: '备学生——初中数学课程标准'
author: "杨端端"
date: 2021-09-10
categories: ["高中数学"]
tags: ["高中数学"]
---

**一、数与代数**

（一）数与式

1. 有理数

（1）理解有理数的意义，能用数轴上的点表示有理数，能比较有理数的大小。

（2）借助数轴理解相反数和绝对值的意义，掌握求有理数的相反数与绝对值的方法，知道 $\vert a\vert$ 的含义（这里 $a$ 表示有理数）。

（3）理解乘方的意义，掌握有理数的加、减、乘、除、乘方及简单的混合运算（以三步以内为主）。

（4）理解有理数的运算律，能运用运算律简化运算。

（5）能运用有理数的运算解决简单的问题。

2. 实数

（1）了解平方根、算术平方根、立方根的概念，会用根号表示数的平方根、算术平方根、立方根。

（2）了解乘方与开方互为逆运算，会用平方运算求百以内整数的平方根，会用立方运算求百以内整数（对应的负整数）的立方根，会用计算器求平方根和立方根。

（3）了解无理数和实数的概念，知道实数与数轴上的点一一对应，能求实数的相反数与绝对值。

（4）能用有理数估计一个无理数的大致范围。

（5）了解近似数，在解决实际问题中，能用计算器进行近似计算，并会按问题的要求对结果取近似值。

（6）了解二次根式、最简二次根式的概念，了解二次根式（根号下仅限于数）加、减、乘、除运算法则，会用它们进行有关的简单四则运算。

3. 代数式

（1）借助现实情景了解代数式，进一步理解用字母表示数的意义。

（2）能分析简单问题中的数量关系，并用代数式表示。

（3）会求代数式的值；能根据特定的问题查阅资料，找到所需要的公式，并会代入具体的值进行计算。

4. 整式与分式

（1）了解整数指数幂的意义和基本性质；会用科学计数法表示数（包括在计算器上表示）。

（2）理解整式的概念，掌握合并同类项和去括号的法则，能进行简单的整式加法和减法运算；能进行简单的整式乘法运算（其中多项式相乘仅指一次式之间以及一次式与二次式相乘）。

（3）能推导乘法公式：$(a+b)(a-b)=a^2-b^2$；$(a\pm b)^2=a^2\pm 2ab+b^2$；了解公式的几何背景，并能利用公式进行简单计算。

（4）能用提公因式法、公式法（直接利用公式不超过二次）进行因式分解（指数是正整数）。

（5）了解分式和最简分式的概念，能利用分式的基本性质进行约分和通分；能进行简单的分式加、减、乘、除运算。

（二）方程与不等式

1. 方程与方程组

（1）能根据具体问题中的数量关系列出方程，体会方程是刻画现实世界数量关系的有效模型。

（2）经历估计方程解的过程。

（3）掌握等式的基本性质。

（4）能解一元一次方程、可化为一元一次方程的分式方程。

（5）掌握代入消元法和加减消元法，能解二元一次方程组。

（6）能解简单的三元一次方程组。

（7）理解配方法，能用配方法、公式法、因式分解法解数字系数的一元二次方程。

（8）会用一元二次方程根的判别式判别方程是否有实根和两个实根是否相等。

（9）了解一元二次方程的根与系数的关系（不要求应用这个关系解决其他问题）。

（10）能根据具体问题的实际意义，检验方程的解是否合理。

2. 不等式与不等式组

（1）结合具体问题，了解不等式的意义，探索不等式的基本性质。

（2）能解数字系数的一元一次不等式，并能在数轴上表示出解集；会用数轴确定由两个一元一次不等式组成的不等式组的解集。

（3）能根据具体问题中的数量关系，列出一元一次不等式，解决简单的问题。

（三）函数

1. 函数

（1）探索简单实例中的数量关系和变化规律，了解常量、变量的意义。

（2）结合实例，了解函数的概念和三种表示法，能举出函数的实例。

（3）能结合图象对简单实际问题中的函数关系进行分析。

（4）能确定简单实际问题中函数自变量的取值范围，并会求出函数值。

（5）能用适当的函数表示法刻画简单实际问题中变量之间的关系。

（6）结合对函数关系的分析，能对变量的变化情况进行初步讨论。

2. 一次函数

（1）结合具体情景体会一次函数的意义，能根据已知条件确定一次函数的表达式。

（2）会利用待定系数法确定一次函数的表达式。

（3）能画出一次函数的图象，能根据一次函数的图象和表达式 $y=kx+b\ (k\neq0)$ 探索并理解 $k>0$ 和 $k<0$ 时，图象的变化情况。

（4）理解正比例函数。

（5）体会一次函数与二元一次方程的关系。

（6）能用一次函数解决简单实际问题。

3. 反比例函数

（1）结合具体情景体会反比例函数的意义，能根据已知条件确定反比例函数的表达式。

（2）能画出反比例函数的图象，根据图象和表达式 $y=\frac{k}{x}\ (k\neq0)$ 探索并理解 $k>0$ 和 $k<0$ 时，图象的变化情况。

（3）能用反比例函数解决简单实际问题。

4. 二次函数

（1）通过对实际问题的分析，体会二次函数的意义。

（2）会用描点法画出二次函数的图象，通过图象了解二次函数的性质。

（3）会用配方法将数字系数的二次函数的表达式化为 $y=a(x-h)^2+k$ 的形式，并能由此得到二次函数图象的顶点坐标，说出图象的开口方向，画出图象的对称轴，并能解决简单实际问题。

（4）会利用二次函数的图象求一元二次方程的近似解。

（5）知道给定不共线三点的坐标可以确定一个二次函数。

**图形与几何**

（一）图形的性质

1. 点、线、面、角

（1）通过实物和具体模型，了解从物体抽象出来的几何体、平面、直线和点等。

（2）会比较线段的长短，理解线段的和、差，以及线段中点的意义。

（3）掌握基本事实：两点确定一条直线。

（4）掌握基本事实：两点之间线段最短。

（5）理解两点间距离的意义，能度量两点间的距离。

（6）理解角的概念，能比较角的大小。

（7）认识度、分、秒，会对度、分、秒进行简单的换算，并会计算角的和、差。

2. 相交线和平行线

（1）理解对顶角、余角、补角等概念，探索并掌握对顶角相等、同角（等角）的余角相等，同角（等角）的补角相等的性质。

（2）理解垂线、垂线段等概念，能用三角尺或量角器过一点画已知直线的垂线。

（3）理解点到直线的距离的意义，能度量点到直线的距离。

（4）掌握基本事实：过一点有且只有一条直线与已知直线垂直。

（5）识别同位角、内错角、同旁内角。

（6）理解平行线概念；掌握基本事实：两条直线被第三条直线所截，如果同位角相等，那么两直线平行。

（7）掌握基本事实：过直线外一点有且只有一条直线与这条直线平行。

（8）掌握平行线的性质定理：两条平行直线被第三条直线所截，同位角相等。了解平行线性质定理的证明。

（9）能用三角尺和直尺过已知直线外一点画这条直线的平行线。

（10）探索并证明平行线的判定定理：两条直线被第三条直线所截，如果内错角相等（或同旁内角互补），那么两直线平行；平行线的性质定理：两条平行直线被第三条直线所截，内错角相等（或同旁内角互补）。

（11）了解平行于同一条直线的liang'tiao